### ISSUE TITLE
springboot的bean管理

### ISSUE THREAD

**Issue by langxuanlove** [cmlbeliever/SpringBootLearning#2]
springboot的bean是不是都是springmvc容器管理的，看官网说的是有@controller/@RestController都是springmvc形式的。springboot中就没有Spring容器管理bean，bean都是在Springmvc容器管理的，这么说对不对？

官网地址：https://docs.spring.io/spring-boot/docs/1.5.5.BUILD-SNAPSHOT/reference/htmlsingle/#using-boot-using-springbootapplication-annotation

**Comment by cmlbeliever** [comment]
感觉你是没理解SpringMvc，SpringBoot与Spring的关系。SpringMvc和SpringBoot都是基于Spring的。至于bean的管理当然都是由Spring容器管理的。
SpringBoot和SpringMvc是没有直接的关系的。
你可以把SpringBoot理解成集成了SpringMvc的一个工具，可以快速启动web服务的工具。

**Comment by langxuanlove** [comment]
主要是我按spring和springmvc容器管理去理解的，springmvc是spring的子容器，所以，
我就想知道，boot中的springmvc的bean是不是都是由子容器springmvc的上下文去管理的,而不是父容器spring管理的。

**Comment by cmlbeliever** [comment]
> boot中的springmvc的bean是不是都是由子容器springmvc的上下文去管理的,而不是父容器spring管理的。
是的
解释如下：
在非SpringBoot环境中，web相关的bean（各种mapping与 adapter）是由子容器springmvc自己管理的
springboot只是将tomcat集成进来，去除了一些繁琐配置而已，原理还是不变的，你可以参考：http://blog.csdn.net/cml_blog/article/details/70196572 springmvc集成过程

**Comment by cmlbeliever** [comment]
以上也只是我的个人理解，还没有实际验证，我会抽个时间验证下。
当然如果你已经找到答案了可以继续交流下

**Comment by cmlbeliever** [comment]
刚才自己特意研究了下得出了结论：
`在Web环境中是由Spring和SpringMvc两个容器组成的，在SpringBoot环境中只有一个容器AnnotationConfigEmbeddedWebApplicationContext。也就是可以说是由SpringBoot容器管理的`
具体分析请看我的博客：http://blog.csdn.net/cml_blog/article/details/78459293
欢迎继续交流

**Comment by langxuanlove** [comment]
之前一直不确定，也没找到如何测试的办法。看了你的分析真是学到不少啊，多谢！多谢！

**Comment by cmlbeliever** [comment]
不客气

**Comment by herriman76** [comment]
看了你的blog，感觉有问题：
“当web容器文不存在时，会去创建一个新的web容器：
protected WebApplicationContext createWebApplicationContext(ApplicationContext parent) {”
-------------------------------------------
而事实上由于FrameworkServlet会aware到父容器，所以它持有的是父容器，不会不存在，不执行createWebApplicationContext。而setParent(rootContext);的时候等于是自己设置自己为父容器。
所以只有一个容器。
